### ISSUE TITLE
create package on pypi

### ISSUE THREAD

**Issue by pmelchior** [aliutkus/torchinterp1d#18]
Thanks for creating and maintaining this package. I recently created a [code](https://github.com/pmelchior/spender) that makes use of `torchinterp1d`. I've released it on PyPI, but that runs into trouble because PyPI doesn't allow direct URLs for code dependencies (see last comment of the relevant issue [here](https://github.com/pypa/twine/issues/726#issuecomment-1087952887)). This has forced me to remove the github URL for your repo from my `setup.py`. But that means that there's no way to automatically download and install your code anymore.

Would it be possible to release your code on PyPI?

**Comment by adam-coogan** [comment]
Bumping this -- it would be quite helpful for me as well!

**Comment by aliutkus** [comment]
Sorry for my reactivity. I am always hoping pytorch will eventually incorporate this... But then checking the many issues I wonder whether we should have them fixed before doing some packaging, shouldn't we?

**Comment by pmelchior** [comment]
It would really help to have this package on pypi, so that your (and my) code could be installed automatically. We're otherwise forced to tool around it. It doesn't change your code at all, which we find to work well, and you can update on pypi easily. I can send you the minimal instructions for getting your package up to pypi if that would help.

**Comment by aliutkus** [comment]
hello, yeah, I guess it would be easier, sorry for that lacking involvement in my github these days. I will do it

**Comment by aliutkus** [comment]
could you try `pip install torchinterp1d` ? I couldn't try but did upload to pypi

**Comment by pmelchior** [comment]
work for me. thank you
